# load("@py_deps//:requirements.bzl", "requirement")
# load("//tools/pytest:defs.bzl", "pytest_test")

# pytest_test(
#     name = "test_get_filter_dict",
#     srcs = ["test_get_filter_dict.py"],
#     deps = [
#         "//app/similarbooks/main:main",
#     ],
# )
